//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proact.Mobile.Core.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Proact.Mobile.Core.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        public static string PickPhotoUnsupportedTitle {
            get {
                return ResourceManager.GetString("PickPhotoUnsupportedTitle", resourceCulture);
            }
        }
        
        public static string PickPhotoUnsupportedMessage {
            get {
                return ResourceManager.GetString("PickPhotoUnsupportedMessage", resourceCulture);
            }
        }
        
        public static string PickPhotoPermissionExceptionMessage {
            get {
                return ResourceManager.GetString("PickPhotoPermissionExceptionMessage", resourceCulture);
            }
        }
        
        public static string TakePhotoCameraUnsupportedTitle {
            get {
                return ResourceManager.GetString("TakePhotoCameraUnsupportedTitle", resourceCulture);
            }
        }
        
        public static string TakePhotoCameraUnsupportedMessage {
            get {
                return ResourceManager.GetString("TakePhotoCameraUnsupportedMessage", resourceCulture);
            }
        }
        
        public static string TakePhotoCameraPermissionExceptionMessage {
            get {
                return ResourceManager.GetString("TakePhotoCameraPermissionExceptionMessage", resourceCulture);
            }
        }
        
        public static string TakePhoto {
            get {
                return ResourceManager.GetString("TakePhoto", resourceCulture);
            }
        }
        
        public static string PickPhoto {
            get {
                return ResourceManager.GetString("PickPhoto", resourceCulture);
            }
        }
        
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        public static string OpenSettings {
            get {
                return ResourceManager.GetString("OpenSettings", resourceCulture);
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        public static string Waiting {
            get {
                return ResourceManager.GetString("Waiting", resourceCulture);
            }
        }
        
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        public static string BodyMessage {
            get {
                return ResourceManager.GetString("BodyMessage", resourceCulture);
            }
        }
        
        public static string YesButton {
            get {
                return ResourceManager.GetString("YesButton", resourceCulture);
            }
        }
        
        public static string NoButton {
            get {
                return ResourceManager.GetString("NoButton", resourceCulture);
            }
        }
        
        public static string SecondsSpan {
            get {
                return ResourceManager.GetString("SecondsSpan", resourceCulture);
            }
        }
        
        public static string MinutesSpan {
            get {
                return ResourceManager.GetString("MinutesSpan", resourceCulture);
            }
        }
        
        public static string HoursSpan {
            get {
                return ResourceManager.GetString("HoursSpan", resourceCulture);
            }
        }
        
        public static string DaysSpan {
            get {
                return ResourceManager.GetString("DaysSpan", resourceCulture);
            }
        }
        
        public static string SearchbarPlaceholder {
            get {
                return ResourceManager.GetString("SearchbarPlaceholder", resourceCulture);
            }
        }
        
        public static string GenericLoadingError {
            get {
                return ResourceManager.GetString("GenericLoadingError", resourceCulture);
            }
        }
        
        public static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        public static string Tagline {
            get {
                return ResourceManager.GetString("Tagline", resourceCulture);
            }
        }
        
        public static string LandingStartButton {
            get {
                return ResourceManager.GetString("LandingStartButton", resourceCulture);
            }
        }
        
        public static string AuthenticationError {
            get {
                return ResourceManager.GetString("AuthenticationError", resourceCulture);
            }
        }
        
        public static string TermsAndConditionsAgreeTitle {
            get {
                return ResourceManager.GetString("TermsAndConditionsAgreeTitle", resourceCulture);
            }
        }
        
        public static string TermsAndConditionsAgreeMessage {
            get {
                return ResourceManager.GetString("TermsAndConditionsAgreeMessage", resourceCulture);
            }
        }
        
        public static string TermsAndConditionsConfirmMessage {
            get {
                return ResourceManager.GetString("TermsAndConditionsConfirmMessage", resourceCulture);
            }
        }
        
        public static string TermsAndConditionsButtonText {
            get {
                return ResourceManager.GetString("TermsAndConditionsButtonText", resourceCulture);
            }
        }
        
        public static string LicenseButtonText {
            get {
                return ResourceManager.GetString("LicenseButtonText", resourceCulture);
            }
        }
        
        public static string TermsAndConditionsError {
            get {
                return ResourceManager.GetString("TermsAndConditionsError", resourceCulture);
            }
        }
        
        public static string TermsConditionsAndLicenseButtonText {
            get {
                return ResourceManager.GetString("TermsConditionsAndLicenseButtonText", resourceCulture);
            }
        }
        
        public static string PrivacyPolicyButtonText {
            get {
                return ResourceManager.GetString("PrivacyPolicyButtonText", resourceCulture);
            }
        }
        
        public static string PrivacyPolicyError {
            get {
                return ResourceManager.GetString("PrivacyPolicyError", resourceCulture);
            }
        }
        
        public static string UrgentMedicalAdviceTitle {
            get {
                return ResourceManager.GetString("UrgentMedicalAdviceTitle", resourceCulture);
            }
        }
        
        public static string UrgentMedicalAdviceMessage {
            get {
                return ResourceManager.GetString("UrgentMedicalAdviceMessage", resourceCulture);
            }
        }
        
        public static string UrgentMedicalAdviceMessage2 {
            get {
                return ResourceManager.GetString("UrgentMedicalAdviceMessage2", resourceCulture);
            }
        }
        
        public static string UrgentMedicalAdviceMessage3 {
            get {
                return ResourceManager.GetString("UrgentMedicalAdviceMessage3", resourceCulture);
            }
        }
        
        public static string UrgentMedicalAdviceCondition {
            get {
                return ResourceManager.GetString("UrgentMedicalAdviceCondition", resourceCulture);
            }
        }
        
        public static string UrgentMedicalAdviceError {
            get {
                return ResourceManager.GetString("UrgentMedicalAdviceError", resourceCulture);
            }
        }
        
        public static string AuthErrorTitle {
            get {
                return ResourceManager.GetString("AuthErrorTitle", resourceCulture);
            }
        }
        
        public static string AuthErrorNoMedicalTeamAssociated {
            get {
                return ResourceManager.GetString("AuthErrorNoMedicalTeamAssociated", resourceCulture);
            }
        }
        
        public static string AuthErrorInvalidMedicalTeam {
            get {
                return ResourceManager.GetString("AuthErrorInvalidMedicalTeam", resourceCulture);
            }
        }
        
        public static string AuthErrorNoProjectAssociated {
            get {
                return ResourceManager.GetString("AuthErrorNoProjectAssociated", resourceCulture);
            }
        }
        
        public static string AuthErrorInvalidProject {
            get {
                return ResourceManager.GetString("AuthErrorInvalidProject", resourceCulture);
            }
        }
        
        public static string AuthErrorUserNotAuthorized {
            get {
                return ResourceManager.GetString("AuthErrorUserNotAuthorized", resourceCulture);
            }
        }
        
        public static string AuthErrorUserInactive {
            get {
                return ResourceManager.GetString("AuthErrorUserInactive", resourceCulture);
            }
        }
        
        public static string ShowAllReplyButtonText {
            get {
                return ResourceManager.GetString("ShowAllReplyButtonText", resourceCulture);
            }
        }
        
        public static string MessageWithVideoAttachmentTitle {
            get {
                return ResourceManager.GetString("MessageWithVideoAttachmentTitle", resourceCulture);
            }
        }
        
        public static string MessageWithVoiceAttachmentTitle {
            get {
                return ResourceManager.GetString("MessageWithVoiceAttachmentTitle", resourceCulture);
            }
        }
        
        public static string NewMessageButton {
            get {
                return ResourceManager.GetString("NewMessageButton", resourceCulture);
            }
        }
        
        public static string NewBroadcastMessageButton {
            get {
                return ResourceManager.GetString("NewBroadcastMessageButton", resourceCulture);
            }
        }
        
        public static string AllMessages {
            get {
                return ResourceManager.GetString("AllMessages", resourceCulture);
            }
        }
        
        public static string NewMessages {
            get {
                return ResourceManager.GetString("NewMessages", resourceCulture);
            }
        }
        
        public static string EmptyWallMessagesMessage {
            get {
                return ResourceManager.GetString("EmptyWallMessagesMessage", resourceCulture);
            }
        }
        
        public static string InfoMessage {
            get {
                return ResourceManager.GetString("InfoMessage", resourceCulture);
            }
        }
        
        public static string HealthMessage {
            get {
                return ResourceManager.GetString("HealthMessage", resourceCulture);
            }
        }
        
        public static string TextTypeMessage {
            get {
                return ResourceManager.GetString("TextTypeMessage", resourceCulture);
            }
        }
        
        public static string VoiceTypeMessage {
            get {
                return ResourceManager.GetString("VoiceTypeMessage", resourceCulture);
            }
        }
        
        public static string VideoTypeMessage {
            get {
                return ResourceManager.GetString("VideoTypeMessage", resourceCulture);
            }
        }
        
        public static string NewTextMessagePageTitle {
            get {
                return ResourceManager.GetString("NewTextMessagePageTitle", resourceCulture);
            }
        }
        
        public static string NewTextMessagePlaceholder {
            get {
                return ResourceManager.GetString("NewTextMessagePlaceholder", resourceCulture);
            }
        }
        
        public static string TitleRequiredError {
            get {
                return ResourceManager.GetString("TitleRequiredError", resourceCulture);
            }
        }
        
        public static string MessageRequiredError {
            get {
                return ResourceManager.GetString("MessageRequiredError", resourceCulture);
            }
        }
        
        public static string NewTextMessageMoodPlaceholder {
            get {
                return ResourceManager.GetString("NewTextMessageMoodPlaceholder", resourceCulture);
            }
        }
        
        public static string NewTextMessageAttachPhotoPlaceholder {
            get {
                return ResourceManager.GetString("NewTextMessageAttachPhotoPlaceholder", resourceCulture);
            }
        }
        
        public static string AttachAnImageToTextMessage {
            get {
                return ResourceManager.GetString("AttachAnImageToTextMessage", resourceCulture);
            }
        }
        
        public static string RemoveAttachedImage {
            get {
                return ResourceManager.GetString("RemoveAttachedImage", resourceCulture);
            }
        }
        
        public static string NewTextMessageSubmitButtonText {
            get {
                return ResourceManager.GetString("NewTextMessageSubmitButtonText", resourceCulture);
            }
        }
        
        public static string MessageSentSuccessfullyAlert {
            get {
                return ResourceManager.GetString("MessageSentSuccessfullyAlert", resourceCulture);
            }
        }
        
        public static string VideoMessageSentSuccessfullyAlert {
            get {
                return ResourceManager.GetString("VideoMessageSentSuccessfullyAlert", resourceCulture);
            }
        }
        
        public static string MediaUploadInitializeAlert {
            get {
                return ResourceManager.GetString("MediaUploadInitializeAlert", resourceCulture);
            }
        }
        
        public static string NewMessageErrorTitle {
            get {
                return ResourceManager.GetString("NewMessageErrorTitle", resourceCulture);
            }
        }
        
        public static string NewMessageErrorMessage {
            get {
                return ResourceManager.GetString("NewMessageErrorMessage", resourceCulture);
            }
        }
        
        public static string VideoMessageUploadSuccess {
            get {
                return ResourceManager.GetString("VideoMessageUploadSuccess", resourceCulture);
            }
        }
        
        public static string VoiceMessageUploadSuccess {
            get {
                return ResourceManager.GetString("VoiceMessageUploadSuccess", resourceCulture);
            }
        }
        
        public static string BradcastMessagePageTitle {
            get {
                return ResourceManager.GetString("BradcastMessagePageTitle", resourceCulture);
            }
        }
        
        public static string BradcastMessageInfo {
            get {
                return ResourceManager.GetString("BradcastMessageInfo", resourceCulture);
            }
        }
        
        public static string MessageUploading {
            get {
                return ResourceManager.GetString("MessageUploading", resourceCulture);
            }
        }
        
        public static string ReplyTextMessagePageTitle {
            get {
                return ResourceManager.GetString("ReplyTextMessagePageTitle", resourceCulture);
            }
        }
        
        public static string ReplyTextMessagePlaceholder {
            get {
                return ResourceManager.GetString("ReplyTextMessagePlaceholder", resourceCulture);
            }
        }
        
        public static string EditTextMessagePageTitle {
            get {
                return ResourceManager.GetString("EditTextMessagePageTitle", resourceCulture);
            }
        }
        
        public static string MessageDetailsPageTitle {
            get {
                return ResourceManager.GetString("MessageDetailsPageTitle", resourceCulture);
            }
        }
        
        public static string DeleteMessageDialogTitle {
            get {
                return ResourceManager.GetString("DeleteMessageDialogTitle", resourceCulture);
            }
        }
        
        public static string DeleteMessageDialogMessage {
            get {
                return ResourceManager.GetString("DeleteMessageDialogMessage", resourceCulture);
            }
        }
        
        public static string ProfilePageTitle {
            get {
                return ResourceManager.GetString("ProfilePageTitle", resourceCulture);
            }
        }
        
        public static string SurveysGroupTitle {
            get {
                return ResourceManager.GetString("SurveysGroupTitle", resourceCulture);
            }
        }
        
        public static string SurveysToBeFillTitle {
            get {
                return ResourceManager.GetString("SurveysToBeFillTitle", resourceCulture);
            }
        }
        
        public static string SurveysFilledInTitle {
            get {
                return ResourceManager.GetString("SurveysFilledInTitle", resourceCulture);
            }
        }
        
        public static string ProtocolDetailsGroupTitle {
            get {
                return ResourceManager.GetString("ProtocolDetailsGroupTitle", resourceCulture);
            }
        }
        
        public static string ProtocolInternationalCode {
            get {
                return ResourceManager.GetString("ProtocolInternationalCode", resourceCulture);
            }
        }
        
        public static string ProtocolInternalCode {
            get {
                return ResourceManager.GetString("ProtocolInternalCode", resourceCulture);
            }
        }
        
        public static string NotificationsGroupTitle {
            get {
                return ResourceManager.GetString("NotificationsGroupTitle", resourceCulture);
            }
        }
        
        public static string ProactInfoGroupTitle {
            get {
                return ResourceManager.GetString("ProactInfoGroupTitle", resourceCulture);
            }
        }
        
        public static string TermsAndConditionsTitle {
            get {
                return ResourceManager.GetString("TermsAndConditionsTitle", resourceCulture);
            }
        }
        
        public static string LicenseTitle {
            get {
                return ResourceManager.GetString("LicenseTitle", resourceCulture);
            }
        }
        
        public static string PrivacyPolicyTitle {
            get {
                return ResourceManager.GetString("PrivacyPolicyTitle", resourceCulture);
            }
        }
        
        public static string TermsAndConditionsAndLicenseTitle {
            get {
                return ResourceManager.GetString("TermsAndConditionsAndLicenseTitle", resourceCulture);
            }
        }
        
        public static string ContactTitle {
            get {
                return ResourceManager.GetString("ContactTitle", resourceCulture);
            }
        }
        
        public static string LogoutGroupTitle {
            get {
                return ResourceManager.GetString("LogoutGroupTitle", resourceCulture);
            }
        }
        
        public static string ExitTitle {
            get {
                return ResourceManager.GetString("ExitTitle", resourceCulture);
            }
        }
        
        public static string AppVersion {
            get {
                return ResourceManager.GetString("AppVersion", resourceCulture);
            }
        }
        
        public static string SignoutAlertTitle {
            get {
                return ResourceManager.GetString("SignoutAlertTitle", resourceCulture);
            }
        }
        
        public static string SignoutAlertMessage {
            get {
                return ResourceManager.GetString("SignoutAlertMessage", resourceCulture);
            }
        }
        
        public static string SignoutAlertOkButton {
            get {
                return ResourceManager.GetString("SignoutAlertOkButton", resourceCulture);
            }
        }
        
        public static string SignoutAlertCancelButton {
            get {
                return ResourceManager.GetString("SignoutAlertCancelButton", resourceCulture);
            }
        }
        
        public static string SelectProfileImage {
            get {
                return ResourceManager.GetString("SelectProfileImage", resourceCulture);
            }
        }
        
        public static string RemoveProfileImage {
            get {
                return ResourceManager.GetString("RemoveProfileImage", resourceCulture);
            }
        }
        
        public static string UploadProfileImageError {
            get {
                return ResourceManager.GetString("UploadProfileImageError", resourceCulture);
            }
        }
        
        public static string UploadProfileImageSuccess {
            get {
                return ResourceManager.GetString("UploadProfileImageSuccess", resourceCulture);
            }
        }
        
        public static string MedicalTeamGroupTitle {
            get {
                return ResourceManager.GetString("MedicalTeamGroupTitle", resourceCulture);
            }
        }
        
        public static string YourPatientsTitle {
            get {
                return ResourceManager.GetString("YourPatientsTitle", resourceCulture);
            }
        }
        
        public static string ChangeMedicalTeamAndTrialTitle {
            get {
                return ResourceManager.GetString("ChangeMedicalTeamAndTrialTitle", resourceCulture);
            }
        }
        
        public static string HelpDeskGroupTitle {
            get {
                return ResourceManager.GetString("HelpDeskGroupTitle", resourceCulture);
            }
        }
        
        public static string HelpDeskPhoneSubtitle {
            get {
                return ResourceManager.GetString("HelpDeskPhoneSubtitle", resourceCulture);
            }
        }
        
        public static string VoiceRecordingTitle {
            get {
                return ResourceManager.GetString("VoiceRecordingTitle", resourceCulture);
            }
        }
        
        public static string TapToStartVoiceReproduction {
            get {
                return ResourceManager.GetString("TapToStartVoiceReproduction", resourceCulture);
            }
        }
        
        public static string TapToStartRecording {
            get {
                return ResourceManager.GetString("TapToStartRecording", resourceCulture);
            }
        }
        
        public static string TapToStopRecording {
            get {
                return ResourceManager.GetString("TapToStopRecording", resourceCulture);
            }
        }
        
        public static string Recording {
            get {
                return ResourceManager.GetString("Recording", resourceCulture);
            }
        }
        
        public static string SendVoiceMessageAlertTitle {
            get {
                return ResourceManager.GetString("SendVoiceMessageAlertTitle", resourceCulture);
            }
        }
        
        public static string SendVoiceMessageAlertMessage {
            get {
                return ResourceManager.GetString("SendVoiceMessageAlertMessage", resourceCulture);
            }
        }
        
        public static string SendVoiceMessageConfirmButton {
            get {
                return ResourceManager.GetString("SendVoiceMessageConfirmButton", resourceCulture);
            }
        }
        
        public static string VoiceRecordingClosePageTitle {
            get {
                return ResourceManager.GetString("VoiceRecordingClosePageTitle", resourceCulture);
            }
        }
        
        public static string VoiceRecordingCloseButton {
            get {
                return ResourceManager.GetString("VoiceRecordingCloseButton", resourceCulture);
            }
        }
        
        public static string VoiceRecordingCancelButton {
            get {
                return ResourceManager.GetString("VoiceRecordingCancelButton", resourceCulture);
            }
        }
        
        public static string VideoPlayerPageTitle {
            get {
                return ResourceManager.GetString("VideoPlayerPageTitle", resourceCulture);
            }
        }
        
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        public static string VoicePlayError {
            get {
                return ResourceManager.GetString("VoicePlayError", resourceCulture);
            }
        }
        
        public static string MicrophonePermissionExceptionTitle {
            get {
                return ResourceManager.GetString("MicrophonePermissionExceptionTitle", resourceCulture);
            }
        }
        
        public static string MicrophonePermissionExceptionMessage {
            get {
                return ResourceManager.GetString("MicrophonePermissionExceptionMessage", resourceCulture);
            }
        }
        
        public static string ProjectsListPageTitle {
            get {
                return ResourceManager.GetString("ProjectsListPageTitle", resourceCulture);
            }
        }
        
        public static string ProjectsListRequestError {
            get {
                return ResourceManager.GetString("ProjectsListRequestError", resourceCulture);
            }
        }
        
        public static string MedicalTeamsListRequestError {
            get {
                return ResourceManager.GetString("MedicalTeamsListRequestError", resourceCulture);
            }
        }
        
        public static string EmptyProjectsListMessage {
            get {
                return ResourceManager.GetString("EmptyProjectsListMessage", resourceCulture);
            }
        }
        
        public static string CompletedSurveysPageTitle {
            get {
                return ResourceManager.GetString("CompletedSurveysPageTitle", resourceCulture);
            }
        }
        
        public static string ToBeCompletedSurveysPageTitle {
            get {
                return ResourceManager.GetString("ToBeCompletedSurveysPageTitle", resourceCulture);
            }
        }
        
        public static string SurveyQuestionsCounterLabel {
            get {
                return ResourceManager.GetString("SurveyQuestionsCounterLabel", resourceCulture);
            }
        }
        
        public static string SurveyQuestionsVersionLabel {
            get {
                return ResourceManager.GetString("SurveyQuestionsVersionLabel", resourceCulture);
            }
        }
        
        public static string SurveyStartButton {
            get {
                return ResourceManager.GetString("SurveyStartButton", resourceCulture);
            }
        }
        
        public static string SurveyQuestionOrderLabel {
            get {
                return ResourceManager.GetString("SurveyQuestionOrderLabel", resourceCulture);
            }
        }
        
        public static string SurveyOpenAswerEditorPlaceholder {
            get {
                return ResourceManager.GetString("SurveyOpenAswerEditorPlaceholder", resourceCulture);
            }
        }
        
        public static string SurveySingleAswerPlaceholder {
            get {
                return ResourceManager.GetString("SurveySingleAswerPlaceholder", resourceCulture);
            }
        }
        
        public static string SurveyMultipleAswersPlaceholder {
            get {
                return ResourceManager.GetString("SurveyMultipleAswersPlaceholder", resourceCulture);
            }
        }
        
        public static string EnterAnswerError {
            get {
                return ResourceManager.GetString("EnterAnswerError", resourceCulture);
            }
        }
        
        public static string SelectAnswerError {
            get {
                return ResourceManager.GetString("SelectAnswerError", resourceCulture);
            }
        }
        
        public static string SubmitSurveyButton {
            get {
                return ResourceManager.GetString("SubmitSurveyButton", resourceCulture);
            }
        }
        
        public static string SurveyResultsGoodMessage {
            get {
                return ResourceManager.GetString("SurveyResultsGoodMessage", resourceCulture);
            }
        }
        
        public static string SurveyResultsBadMessage {
            get {
                return ResourceManager.GetString("SurveyResultsBadMessage", resourceCulture);
            }
        }
        
        public static string SurveyCheckPageTitle {
            get {
                return ResourceManager.GetString("SurveyCheckPageTitle", resourceCulture);
            }
        }
        
        public static string SurveyExpires {
            get {
                return ResourceManager.GetString("SurveyExpires", resourceCulture);
            }
        }
        
        public static string SurveyCompleted {
            get {
                return ResourceManager.GetString("SurveyCompleted", resourceCulture);
            }
        }
        
        public static string EmptyNotComiledSurveysList {
            get {
                return ResourceManager.GetString("EmptyNotComiledSurveysList", resourceCulture);
            }
        }
        
        public static string EmptyComiledSurveysList {
            get {
                return ResourceManager.GetString("EmptyComiledSurveysList", resourceCulture);
            }
        }
        
        public static string PatientsListRequestError {
            get {
                return ResourceManager.GetString("PatientsListRequestError", resourceCulture);
            }
        }
        
        public static string EmptyPatientsListMessage {
            get {
                return ResourceManager.GetString("EmptyPatientsListMessage", resourceCulture);
            }
        }
        
        public static string NotificationMediaUploadTitle {
            get {
                return ResourceManager.GetString("NotificationMediaUploadTitle", resourceCulture);
            }
        }
        
        public static string NotificationMessageMediaUploading {
            get {
                return ResourceManager.GetString("NotificationMessageMediaUploading", resourceCulture);
            }
        }
        
        public static string NotificationMessageMediaVerification {
            get {
                return ResourceManager.GetString("NotificationMessageMediaVerification", resourceCulture);
            }
        }
        
        public static string NotificationMessageMediaUploaded {
            get {
                return ResourceManager.GetString("NotificationMessageMediaUploaded", resourceCulture);
            }
        }
        
        public static string PatientDetailsSurveysCompleted {
            get {
                return ResourceManager.GetString("PatientDetailsSurveysCompleted", resourceCulture);
            }
        }
        
        public static string PatientDetailsMediaList {
            get {
                return ResourceManager.GetString("PatientDetailsMediaList", resourceCulture);
            }
        }
        
        public static string SearchPageTitle {
            get {
                return ResourceManager.GetString("SearchPageTitle", resourceCulture);
            }
        }
        
        public static string SearchPagePlaceholder {
            get {
                return ResourceManager.GetString("SearchPagePlaceholder", resourceCulture);
            }
        }
        
        public static string EmptySearchMessageResult {
            get {
                return ResourceManager.GetString("EmptySearchMessageResult", resourceCulture);
            }
        }
        
        public static string TopicType {
            get {
                return ResourceManager.GetString("TopicType", resourceCulture);
            }
        }
        
        public static string CommentType {
            get {
                return ResourceManager.GetString("CommentType", resourceCulture);
            }
        }
        
        public static string BroadcastType {
            get {
                return ResourceManager.GetString("BroadcastType", resourceCulture);
            }
        }
        
        public static string NotificationsOptionsPageTitle {
            get {
                return ResourceManager.GetString("NotificationsOptionsPageTitle", resourceCulture);
            }
        }
        
        public static string AllowNotifications {
            get {
                return ResourceManager.GetString("AllowNotifications", resourceCulture);
            }
        }
        
        public static string NotificationsReceivingTime {
            get {
                return ResourceManager.GetString("NotificationsReceivingTime", resourceCulture);
            }
        }
        
        public static string NotificationsTimeFrom {
            get {
                return ResourceManager.GetString("NotificationsTimeFrom", resourceCulture);
            }
        }
        
        public static string NotificationsTimeTo {
            get {
                return ResourceManager.GetString("NotificationsTimeTo", resourceCulture);
            }
        }
        
        public static string UnlimitedNotificationsTime {
            get {
                return ResourceManager.GetString("UnlimitedNotificationsTime", resourceCulture);
            }
        }
        
        public static string NotificationSettingsPageTitle {
            get {
                return ResourceManager.GetString("NotificationSettingsPageTitle", resourceCulture);
            }
        }
        
        public static string NotificationSettingsInfo {
            get {
                return ResourceManager.GetString("NotificationSettingsInfo", resourceCulture);
            }
        }
        
        public static string PushNotificationsSettingsValidateError {
            get {
                return ResourceManager.GetString("PushNotificationsSettingsValidateError", resourceCulture);
            }
        }
        
        public static string RemovePushNotificationTimeLimit {
            get {
                return ResourceManager.GetString("RemovePushNotificationTimeLimit", resourceCulture);
            }
        }
        
        public static string MedicalTeamsListPageTitle {
            get {
                return ResourceManager.GetString("MedicalTeamsListPageTitle", resourceCulture);
            }
        }
        
        public static string EmptyMedicalTeamsListMessage {
            get {
                return ResourceManager.GetString("EmptyMedicalTeamsListMessage", resourceCulture);
            }
        }
        
        public static string NotDeletableMessageAlertTitle {
            get {
                return ResourceManager.GetString("NotDeletableMessageAlertTitle", resourceCulture);
            }
        }
        
        public static string NotDeletableMessageAlertMessage {
            get {
                return ResourceManager.GetString("NotDeletableMessageAlertMessage", resourceCulture);
            }
        }
        
        public static string CantReplyToMessageAlertTitle {
            get {
                return ResourceManager.GetString("CantReplyToMessageAlertTitle", resourceCulture);
            }
        }
        
        public static string CantReplyToMessageAlertMessage {
            get {
                return ResourceManager.GetString("CantReplyToMessageAlertMessage", resourceCulture);
            }
        }
        
        public static string AddAnalysisButton {
            get {
                return ResourceManager.GetString("AddAnalysisButton", resourceCulture);
            }
        }
        
        public static string AnalysisListPageTitle {
            get {
                return ResourceManager.GetString("AnalysisListPageTitle", resourceCulture);
            }
        }
        
        public static string CantAnalyzeMessageAlertTitle {
            get {
                return ResourceManager.GetString("CantAnalyzeMessageAlertTitle", resourceCulture);
            }
        }
        
        public static string CantAnalyzeMessageAlertMessage {
            get {
                return ResourceManager.GetString("CantAnalyzeMessageAlertMessage", resourceCulture);
            }
        }
        
        public static string AddAnalysisPageTitle {
            get {
                return ResourceManager.GetString("AddAnalysisPageTitle", resourceCulture);
            }
        }
        
        public static string AddAnalysisButtonText {
            get {
                return ResourceManager.GetString("AddAnalysisButtonText", resourceCulture);
            }
        }
        
        public static string AddAnalysisAlertMessage {
            get {
                return ResourceManager.GetString("AddAnalysisAlertMessage", resourceCulture);
            }
        }
        
        public static string AddAnalysisAlertConfirmButton {
            get {
                return ResourceManager.GetString("AddAnalysisAlertConfirmButton", resourceCulture);
            }
        }
        
        public static string AddAnalysisAlertTitle {
            get {
                return ResourceManager.GetString("AddAnalysisAlertTitle", resourceCulture);
            }
        }
        
        public static string AnalysisLabelAlreadyExistAlertMessage {
            get {
                return ResourceManager.GetString("AnalysisLabelAlreadyExistAlertMessage", resourceCulture);
            }
        }
        
        public static string AddAnalysisMessageError {
            get {
                return ResourceManager.GetString("AddAnalysisMessageError", resourceCulture);
            }
        }
        
        public static string AddAnalysisSuccessAlertMessage {
            get {
                return ResourceManager.GetString("AddAnalysisSuccessAlertMessage", resourceCulture);
            }
        }
        
        public static string AnalysisGroupPageTitle {
            get {
                return ResourceManager.GetString("AnalysisGroupPageTitle", resourceCulture);
            }
        }
        
        public static string AnalysisGroupFilterActiveMessage {
            get {
                return ResourceManager.GetString("AnalysisGroupFilterActiveMessage", resourceCulture);
            }
        }
        
        public static string AnalysisGroupRemoveFilter {
            get {
                return ResourceManager.GetString("AnalysisGroupRemoveFilter", resourceCulture);
            }
        }
        
        public static string AnalysisGroupButton {
            get {
                return ResourceManager.GetString("AnalysisGroupButton", resourceCulture);
            }
        }
        
        public static string AnalysisDeleteAlertTitle {
            get {
                return ResourceManager.GetString("AnalysisDeleteAlertTitle", resourceCulture);
            }
        }
        
        public static string AnalysisDeleteAlertMessage {
            get {
                return ResourceManager.GetString("AnalysisDeleteAlertMessage", resourceCulture);
            }
        }
        
        public static string AnalysisDeleteErrorMessage {
            get {
                return ResourceManager.GetString("AnalysisDeleteErrorMessage", resourceCulture);
            }
        }
        
        public static string EmptyList {
            get {
                return ResourceManager.GetString("EmptyList", resourceCulture);
            }
        }
        
        public static string EditAnalysisPageTitle {
            get {
                return ResourceManager.GetString("EditAnalysisPageTitle", resourceCulture);
            }
        }
        
        public static string UpdateAnalysisAlertTitle {
            get {
                return ResourceManager.GetString("UpdateAnalysisAlertTitle", resourceCulture);
            }
        }
        
        public static string UpdateAnalysisAlertMessage {
            get {
                return ResourceManager.GetString("UpdateAnalysisAlertMessage", resourceCulture);
            }
        }
        
        public static string UpdateAnalysisAlertConfirmButton {
            get {
                return ResourceManager.GetString("UpdateAnalysisAlertConfirmButton", resourceCulture);
            }
        }
        
        public static string UpdateAnalysisSuccessAlertMessage {
            get {
                return ResourceManager.GetString("UpdateAnalysisSuccessAlertMessage", resourceCulture);
            }
        }
        
        public static string AddAnalysisValidationError {
            get {
                return ResourceManager.GetString("AddAnalysisValidationError", resourceCulture);
            }
        }
        
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        public static string UserCantSignin {
            get {
                return ResourceManager.GetString("UserCantSignin", resourceCulture);
            }
        }
        
        public static string UserCantReplyToMessage {
            get {
                return ResourceManager.GetString("UserCantReplyToMessage", resourceCulture);
            }
        }
        
        public static string LoginDocumentsUnavaliable {
            get {
                return ResourceManager.GetString("LoginDocumentsUnavaliable", resourceCulture);
            }
        }
        
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        public static string Deactivated {
            get {
                return ResourceManager.GetString("Deactivated", resourceCulture);
            }
        }
        
        public static string Suspended {
            get {
                return ResourceManager.GetString("Suspended", resourceCulture);
            }
        }
        
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        public static string UpdateDiscaimer {
            get {
                return ResourceManager.GetString("UpdateDiscaimer", resourceCulture);
            }
        }
        
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        public static string Tomorrow {
            get {
                return ResourceManager.GetString("Tomorrow", resourceCulture);
            }
        }
        
        public static string SurveysStats {
            get {
                return ResourceManager.GetString("SurveysStats", resourceCulture);
            }
        }
        
        public static string SurveysPartecipants {
            get {
                return ResourceManager.GetString("SurveysPartecipants", resourceCulture);
            }
        }
        
        public static string CompletedSurvey {
            get {
                return ResourceManager.GetString("CompletedSurvey", resourceCulture);
            }
        }
        
        public static string IncompletedSurvey {
            get {
                return ResourceManager.GetString("IncompletedSurvey", resourceCulture);
            }
        }
        
        public static string CompletedSurveys {
            get {
                return ResourceManager.GetString("CompletedSurveys", resourceCulture);
            }
        }
        
        public static string IncompletedSurveys {
            get {
                return ResourceManager.GetString("IncompletedSurveys", resourceCulture);
            }
        }
        
        public static string SurveysListPageTitle {
            get {
                return ResourceManager.GetString("SurveysListPageTitle", resourceCulture);
            }
        }
        
        public static string SurveysResultsAndStatistics {
            get {
                return ResourceManager.GetString("SurveysResultsAndStatistics", resourceCulture);
            }
        }
        
        public static string SurveysNotCompiledError {
            get {
                return ResourceManager.GetString("SurveysNotCompiledError", resourceCulture);
            }
        }
        
        public static string SurveysResults {
            get {
                return ResourceManager.GetString("SurveysResults", resourceCulture);
            }
        }
        
        public static string SurveysStatistics {
            get {
                return ResourceManager.GetString("SurveysStatistics", resourceCulture);
            }
        }
    }
}
