//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proact.Mobile.Core.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources_de {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_de() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Proact.Mobile.Core.Resources.AppResources.de", typeof(AppResources_de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AddAnalysisAlertConfirmButton {
            get {
                return ResourceManager.GetString("AddAnalysisAlertConfirmButton", resourceCulture);
            }
        }
        
        internal static string AddAnalysisAlertMessage {
            get {
                return ResourceManager.GetString("AddAnalysisAlertMessage", resourceCulture);
            }
        }
        
        internal static string AddAnalysisAlertTitle {
            get {
                return ResourceManager.GetString("AddAnalysisAlertTitle", resourceCulture);
            }
        }
        
        internal static string AddAnalysisButton {
            get {
                return ResourceManager.GetString("AddAnalysisButton", resourceCulture);
            }
        }
        
        internal static string AddAnalysisButtonText {
            get {
                return ResourceManager.GetString("AddAnalysisButtonText", resourceCulture);
            }
        }
        
        internal static string AddAnalysisMessageError {
            get {
                return ResourceManager.GetString("AddAnalysisMessageError", resourceCulture);
            }
        }
        
        internal static string AddAnalysisPageTitle {
            get {
                return ResourceManager.GetString("AddAnalysisPageTitle", resourceCulture);
            }
        }
        
        internal static string AddAnalysisSuccessAlertMessage {
            get {
                return ResourceManager.GetString("AddAnalysisSuccessAlertMessage", resourceCulture);
            }
        }
        
        internal static string AddAnalysisValidationError {
            get {
                return ResourceManager.GetString("AddAnalysisValidationError", resourceCulture);
            }
        }
        
        internal static string AllMessages {
            get {
                return ResourceManager.GetString("AllMessages", resourceCulture);
            }
        }
        
        internal static string AllowNotifications {
            get {
                return ResourceManager.GetString("AllowNotifications", resourceCulture);
            }
        }
        
        internal static string AnalysisDeleteAlertMessage {
            get {
                return ResourceManager.GetString("AnalysisDeleteAlertMessage", resourceCulture);
            }
        }
        
        internal static string AnalysisDeleteAlertTitle {
            get {
                return ResourceManager.GetString("AnalysisDeleteAlertTitle", resourceCulture);
            }
        }
        
        internal static string AnalysisDeleteErrorMessage {
            get {
                return ResourceManager.GetString("AnalysisDeleteErrorMessage", resourceCulture);
            }
        }
        
        internal static string AnalysisGroupButton {
            get {
                return ResourceManager.GetString("AnalysisGroupButton", resourceCulture);
            }
        }
        
        internal static string AnalysisGroupFilterActiveMessage {
            get {
                return ResourceManager.GetString("AnalysisGroupFilterActiveMessage", resourceCulture);
            }
        }
        
        internal static string AnalysisGroupPageTitle {
            get {
                return ResourceManager.GetString("AnalysisGroupPageTitle", resourceCulture);
            }
        }
        
        internal static string AnalysisGroupRemoveFilter {
            get {
                return ResourceManager.GetString("AnalysisGroupRemoveFilter", resourceCulture);
            }
        }
        
        internal static string AnalysisLabelAlreadyExistAlertMessage {
            get {
                return ResourceManager.GetString("AnalysisLabelAlreadyExistAlertMessage", resourceCulture);
            }
        }
        
        internal static string AnalysisListPageTitle {
            get {
                return ResourceManager.GetString("AnalysisListPageTitle", resourceCulture);
            }
        }
        
        internal static string AppVersion {
            get {
                return ResourceManager.GetString("AppVersion", resourceCulture);
            }
        }
        
        internal static string AttachAnImageToTextMessage {
            get {
                return ResourceManager.GetString("AttachAnImageToTextMessage", resourceCulture);
            }
        }
        
        internal static string AuthenticationError {
            get {
                return ResourceManager.GetString("AuthenticationError", resourceCulture);
            }
        }
        
        internal static string AuthErrorInvalidMedicalTeam {
            get {
                return ResourceManager.GetString("AuthErrorInvalidMedicalTeam", resourceCulture);
            }
        }
        
        internal static string AuthErrorInvalidProject {
            get {
                return ResourceManager.GetString("AuthErrorInvalidProject", resourceCulture);
            }
        }
        
        internal static string AuthErrorNoMedicalTeamAssociated {
            get {
                return ResourceManager.GetString("AuthErrorNoMedicalTeamAssociated", resourceCulture);
            }
        }
        
        internal static string AuthErrorNoProjectAssociated {
            get {
                return ResourceManager.GetString("AuthErrorNoProjectAssociated", resourceCulture);
            }
        }
        
        internal static string AuthErrorTitle {
            get {
                return ResourceManager.GetString("AuthErrorTitle", resourceCulture);
            }
        }
        
        internal static string AuthErrorUserInactive {
            get {
                return ResourceManager.GetString("AuthErrorUserInactive", resourceCulture);
            }
        }
        
        internal static string AuthErrorUserNotAuthorized {
            get {
                return ResourceManager.GetString("AuthErrorUserNotAuthorized", resourceCulture);
            }
        }
        
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        internal static string BodyMessage {
            get {
                return ResourceManager.GetString("BodyMessage", resourceCulture);
            }
        }
        
        internal static string BradcastMessageInfo {
            get {
                return ResourceManager.GetString("BradcastMessageInfo", resourceCulture);
            }
        }
        
        internal static string BradcastMessagePageTitle {
            get {
                return ResourceManager.GetString("BradcastMessagePageTitle", resourceCulture);
            }
        }
        
        internal static string BroadcastType {
            get {
                return ResourceManager.GetString("BroadcastType", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string CantAnalyzeMessageAlertMessage {
            get {
                return ResourceManager.GetString("CantAnalyzeMessageAlertMessage", resourceCulture);
            }
        }
        
        internal static string CantAnalyzeMessageAlertTitle {
            get {
                return ResourceManager.GetString("CantAnalyzeMessageAlertTitle", resourceCulture);
            }
        }
        
        internal static string CantReplyToMessageAlertMessage {
            get {
                return ResourceManager.GetString("CantReplyToMessageAlertMessage", resourceCulture);
            }
        }
        
        internal static string CantReplyToMessageAlertTitle {
            get {
                return ResourceManager.GetString("CantReplyToMessageAlertTitle", resourceCulture);
            }
        }
        
        internal static string ChangeMedicalTeamAndTrialTitle {
            get {
                return ResourceManager.GetString("ChangeMedicalTeamAndTrialTitle", resourceCulture);
            }
        }
        
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        internal static string CommentType {
            get {
                return ResourceManager.GetString("CommentType", resourceCulture);
            }
        }
        
        internal static string CompletedSurveysPageTitle {
            get {
                return ResourceManager.GetString("CompletedSurveysPageTitle", resourceCulture);
            }
        }
        
        internal static string ContactTitle {
            get {
                return ResourceManager.GetString("ContactTitle", resourceCulture);
            }
        }
        
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        internal static string DaysSpan {
            get {
                return ResourceManager.GetString("DaysSpan", resourceCulture);
            }
        }
        
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        internal static string DeleteMessageDialogMessage {
            get {
                return ResourceManager.GetString("DeleteMessageDialogMessage", resourceCulture);
            }
        }
        
        internal static string DeleteMessageDialogTitle {
            get {
                return ResourceManager.GetString("DeleteMessageDialogTitle", resourceCulture);
            }
        }
        
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        internal static string EditAnalysisPageTitle {
            get {
                return ResourceManager.GetString("EditAnalysisPageTitle", resourceCulture);
            }
        }
        
        internal static string EditTextMessagePageTitle {
            get {
                return ResourceManager.GetString("EditTextMessagePageTitle", resourceCulture);
            }
        }
        
        internal static string EmptyComiledSurveysList {
            get {
                return ResourceManager.GetString("EmptyComiledSurveysList", resourceCulture);
            }
        }
        
        internal static string EmptyList {
            get {
                return ResourceManager.GetString("EmptyList", resourceCulture);
            }
        }
        
        internal static string EmptyMedicalTeamsListMessage {
            get {
                return ResourceManager.GetString("EmptyMedicalTeamsListMessage", resourceCulture);
            }
        }
        
        internal static string EmptyNotComiledSurveysList {
            get {
                return ResourceManager.GetString("EmptyNotComiledSurveysList", resourceCulture);
            }
        }
        
        internal static string EmptyPatientsListMessage {
            get {
                return ResourceManager.GetString("EmptyPatientsListMessage", resourceCulture);
            }
        }
        
        internal static string EmptyProjectsListMessage {
            get {
                return ResourceManager.GetString("EmptyProjectsListMessage", resourceCulture);
            }
        }
        
        internal static string EmptySearchMessageResult {
            get {
                return ResourceManager.GetString("EmptySearchMessageResult", resourceCulture);
            }
        }
        
        internal static string EmptyWallMessagesMessage {
            get {
                return ResourceManager.GetString("EmptyWallMessagesMessage", resourceCulture);
            }
        }
        
        internal static string EnterAnswerError {
            get {
                return ResourceManager.GetString("EnterAnswerError", resourceCulture);
            }
        }
        
        internal static string ExitTitle {
            get {
                return ResourceManager.GetString("ExitTitle", resourceCulture);
            }
        }
        
        internal static string GenericLoadingError {
            get {
                return ResourceManager.GetString("GenericLoadingError", resourceCulture);
            }
        }
        
        internal static string HealthMessage {
            get {
                return ResourceManager.GetString("HealthMessage", resourceCulture);
            }
        }
        
        internal static string HelpDeskGroupTitle {
            get {
                return ResourceManager.GetString("HelpDeskGroupTitle", resourceCulture);
            }
        }
        
        internal static string HelpDeskPhoneSubtitle {
            get {
                return ResourceManager.GetString("HelpDeskPhoneSubtitle", resourceCulture);
            }
        }
        
        internal static string HoursSpan {
            get {
                return ResourceManager.GetString("HoursSpan", resourceCulture);
            }
        }
        
        internal static string InfoMessage {
            get {
                return ResourceManager.GetString("InfoMessage", resourceCulture);
            }
        }
        
        internal static string LandingStartButton {
            get {
                return ResourceManager.GetString("LandingStartButton", resourceCulture);
            }
        }
        
        internal static string LicenseButtonText {
            get {
                return ResourceManager.GetString("LicenseButtonText", resourceCulture);
            }
        }
        
        internal static string LicenseTitle {
            get {
                return ResourceManager.GetString("LicenseTitle", resourceCulture);
            }
        }
        
        internal static string LogoutGroupTitle {
            get {
                return ResourceManager.GetString("LogoutGroupTitle", resourceCulture);
            }
        }
        
        internal static string MediaUploadInitializeAlert {
            get {
                return ResourceManager.GetString("MediaUploadInitializeAlert", resourceCulture);
            }
        }
        
        internal static string MedicalTeamGroupTitle {
            get {
                return ResourceManager.GetString("MedicalTeamGroupTitle", resourceCulture);
            }
        }
        
        internal static string MedicalTeamsListPageTitle {
            get {
                return ResourceManager.GetString("MedicalTeamsListPageTitle", resourceCulture);
            }
        }
        
        internal static string MedicalTeamsListRequestError {
            get {
                return ResourceManager.GetString("MedicalTeamsListRequestError", resourceCulture);
            }
        }
        
        internal static string MessageDetailsPageTitle {
            get {
                return ResourceManager.GetString("MessageDetailsPageTitle", resourceCulture);
            }
        }
        
        internal static string MessageRequiredError {
            get {
                return ResourceManager.GetString("MessageRequiredError", resourceCulture);
            }
        }
        
        internal static string MessageSentSuccessfullyAlert {
            get {
                return ResourceManager.GetString("MessageSentSuccessfullyAlert", resourceCulture);
            }
        }
        
        internal static string VideoMessageSentSuccessfullyAlert {
            get {
                return ResourceManager.GetString("VideoMessageSentSuccessfullyAlert", resourceCulture);
            }
        }
        
        internal static string MessageUploading {
            get {
                return ResourceManager.GetString("MessageUploading", resourceCulture);
            }
        }
        
        internal static string MessageWithVideoAttachmentTitle {
            get {
                return ResourceManager.GetString("MessageWithVideoAttachmentTitle", resourceCulture);
            }
        }
        
        internal static string MessageWithVoiceAttachmentTitle {
            get {
                return ResourceManager.GetString("MessageWithVoiceAttachmentTitle", resourceCulture);
            }
        }
        
        internal static string MicrophonePermissionExceptionMessage {
            get {
                return ResourceManager.GetString("MicrophonePermissionExceptionMessage", resourceCulture);
            }
        }
        
        internal static string MicrophonePermissionExceptionTitle {
            get {
                return ResourceManager.GetString("MicrophonePermissionExceptionTitle", resourceCulture);
            }
        }
        
        internal static string MinutesSpan {
            get {
                return ResourceManager.GetString("MinutesSpan", resourceCulture);
            }
        }
        
        internal static string NewBroadcastMessageButton {
            get {
                return ResourceManager.GetString("NewBroadcastMessageButton", resourceCulture);
            }
        }
        
        internal static string NewMessageButton {
            get {
                return ResourceManager.GetString("NewMessageButton", resourceCulture);
            }
        }
        
        internal static string NewMessageErrorMessage {
            get {
                return ResourceManager.GetString("NewMessageErrorMessage", resourceCulture);
            }
        }
        
        internal static string NewMessageErrorTitle {
            get {
                return ResourceManager.GetString("NewMessageErrorTitle", resourceCulture);
            }
        }
        
        internal static string NewMessages {
            get {
                return ResourceManager.GetString("NewMessages", resourceCulture);
            }
        }
        
        internal static string NewTextMessageAttachPhotoPlaceholder {
            get {
                return ResourceManager.GetString("NewTextMessageAttachPhotoPlaceholder", resourceCulture);
            }
        }
        
        internal static string NewTextMessageMoodPlaceholder {
            get {
                return ResourceManager.GetString("NewTextMessageMoodPlaceholder", resourceCulture);
            }
        }
        
        internal static string NewTextMessagePageTitle {
            get {
                return ResourceManager.GetString("NewTextMessagePageTitle", resourceCulture);
            }
        }
        
        internal static string NewTextMessagePlaceholder {
            get {
                return ResourceManager.GetString("NewTextMessagePlaceholder", resourceCulture);
            }
        }
        
        internal static string NewTextMessageSubmitButtonText {
            get {
                return ResourceManager.GetString("NewTextMessageSubmitButtonText", resourceCulture);
            }
        }
        
        internal static string NoButton {
            get {
                return ResourceManager.GetString("NoButton", resourceCulture);
            }
        }
        
        internal static string NotDeletableMessageAlertMessage {
            get {
                return ResourceManager.GetString("NotDeletableMessageAlertMessage", resourceCulture);
            }
        }
        
        internal static string NotDeletableMessageAlertTitle {
            get {
                return ResourceManager.GetString("NotDeletableMessageAlertTitle", resourceCulture);
            }
        }
        
        internal static string NotificationMediaUploadTitle {
            get {
                return ResourceManager.GetString("NotificationMediaUploadTitle", resourceCulture);
            }
        }
        
        internal static string NotificationMessageMediaUploaded {
            get {
                return ResourceManager.GetString("NotificationMessageMediaUploaded", resourceCulture);
            }
        }
        
        internal static string NotificationMessageMediaUploading {
            get {
                return ResourceManager.GetString("NotificationMessageMediaUploading", resourceCulture);
            }
        }
        
        internal static string NotificationMessageMediaVerification {
            get {
                return ResourceManager.GetString("NotificationMessageMediaVerification", resourceCulture);
            }
        }
        
        internal static string NotificationSettingsInfo {
            get {
                return ResourceManager.GetString("NotificationSettingsInfo", resourceCulture);
            }
        }
        
        internal static string NotificationSettingsPageTitle {
            get {
                return ResourceManager.GetString("NotificationSettingsPageTitle", resourceCulture);
            }
        }
        
        internal static string NotificationsGroupTitle {
            get {
                return ResourceManager.GetString("NotificationsGroupTitle", resourceCulture);
            }
        }
        
        internal static string NotificationsOptionsPageTitle {
            get {
                return ResourceManager.GetString("NotificationsOptionsPageTitle", resourceCulture);
            }
        }
        
        internal static string NotificationsReceivingTime {
            get {
                return ResourceManager.GetString("NotificationsReceivingTime", resourceCulture);
            }
        }
        
        internal static string NotificationsTimeFrom {
            get {
                return ResourceManager.GetString("NotificationsTimeFrom", resourceCulture);
            }
        }
        
        internal static string NotificationsTimeTo {
            get {
                return ResourceManager.GetString("NotificationsTimeTo", resourceCulture);
            }
        }
        
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        internal static string OpenSettings {
            get {
                return ResourceManager.GetString("OpenSettings", resourceCulture);
            }
        }
        
        internal static string PatientDetailsMediaList {
            get {
                return ResourceManager.GetString("PatientDetailsMediaList", resourceCulture);
            }
        }
        
        internal static string PatientDetailsSurveysCompleted {
            get {
                return ResourceManager.GetString("PatientDetailsSurveysCompleted", resourceCulture);
            }
        }
        
        internal static string PatientsListRequestError {
            get {
                return ResourceManager.GetString("PatientsListRequestError", resourceCulture);
            }
        }
        
        internal static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        internal static string PickPhoto {
            get {
                return ResourceManager.GetString("PickPhoto", resourceCulture);
            }
        }
        
        internal static string PickPhotoPermissionExceptionMessage {
            get {
                return ResourceManager.GetString("PickPhotoPermissionExceptionMessage", resourceCulture);
            }
        }
        
        internal static string PickPhotoUnsupportedMessage {
            get {
                return ResourceManager.GetString("PickPhotoUnsupportedMessage", resourceCulture);
            }
        }
        
        internal static string PickPhotoUnsupportedTitle {
            get {
                return ResourceManager.GetString("PickPhotoUnsupportedTitle", resourceCulture);
            }
        }
        
        internal static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        internal static string PrivacyPolicyButtonText {
            get {
                return ResourceManager.GetString("PrivacyPolicyButtonText", resourceCulture);
            }
        }
        
        internal static string PrivacyPolicyError {
            get {
                return ResourceManager.GetString("PrivacyPolicyError", resourceCulture);
            }
        }
        
        internal static string PrivacyPolicyTitle {
            get {
                return ResourceManager.GetString("PrivacyPolicyTitle", resourceCulture);
            }
        }
        
        internal static string ProactInfoGroupTitle {
            get {
                return ResourceManager.GetString("ProactInfoGroupTitle", resourceCulture);
            }
        }
        
        internal static string ProfilePageTitle {
            get {
                return ResourceManager.GetString("ProfilePageTitle", resourceCulture);
            }
        }
        
        internal static string ProjectsListPageTitle {
            get {
                return ResourceManager.GetString("ProjectsListPageTitle", resourceCulture);
            }
        }
        
        internal static string ProjectsListRequestError {
            get {
                return ResourceManager.GetString("ProjectsListRequestError", resourceCulture);
            }
        }
        
        internal static string ProtocolDetailsGroupTitle {
            get {
                return ResourceManager.GetString("ProtocolDetailsGroupTitle", resourceCulture);
            }
        }
        
        internal static string ProtocolInternalCode {
            get {
                return ResourceManager.GetString("ProtocolInternalCode", resourceCulture);
            }
        }
        
        internal static string ProtocolInternationalCode {
            get {
                return ResourceManager.GetString("ProtocolInternationalCode", resourceCulture);
            }
        }
        
        internal static string PushNotificationsSettingsValidateError {
            get {
                return ResourceManager.GetString("PushNotificationsSettingsValidateError", resourceCulture);
            }
        }
        
        internal static string Recording {
            get {
                return ResourceManager.GetString("Recording", resourceCulture);
            }
        }
        
        internal static string RemoveAttachedImage {
            get {
                return ResourceManager.GetString("RemoveAttachedImage", resourceCulture);
            }
        }
        
        internal static string RemoveProfileImage {
            get {
                return ResourceManager.GetString("RemoveProfileImage", resourceCulture);
            }
        }
        
        internal static string RemovePushNotificationTimeLimit {
            get {
                return ResourceManager.GetString("RemovePushNotificationTimeLimit", resourceCulture);
            }
        }
        
        internal static string ReplyTextMessagePageTitle {
            get {
                return ResourceManager.GetString("ReplyTextMessagePageTitle", resourceCulture);
            }
        }
        
        internal static string ReplyTextMessagePlaceholder {
            get {
                return ResourceManager.GetString("ReplyTextMessagePlaceholder", resourceCulture);
            }
        }
        
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        internal static string SearchbarPlaceholder {
            get {
                return ResourceManager.GetString("SearchbarPlaceholder", resourceCulture);
            }
        }
        
        internal static string SearchPagePlaceholder {
            get {
                return ResourceManager.GetString("SearchPagePlaceholder", resourceCulture);
            }
        }
        
        internal static string SearchPageTitle {
            get {
                return ResourceManager.GetString("SearchPageTitle", resourceCulture);
            }
        }
        
        internal static string SecondsSpan {
            get {
                return ResourceManager.GetString("SecondsSpan", resourceCulture);
            }
        }
        
        internal static string SelectAnswerError {
            get {
                return ResourceManager.GetString("SelectAnswerError", resourceCulture);
            }
        }
        
        internal static string SelectProfileImage {
            get {
                return ResourceManager.GetString("SelectProfileImage", resourceCulture);
            }
        }
        
        internal static string SendVoiceMessageAlertMessage {
            get {
                return ResourceManager.GetString("SendVoiceMessageAlertMessage", resourceCulture);
            }
        }
        
        internal static string SendVoiceMessageAlertTitle {
            get {
                return ResourceManager.GetString("SendVoiceMessageAlertTitle", resourceCulture);
            }
        }
        
        internal static string SendVoiceMessageConfirmButton {
            get {
                return ResourceManager.GetString("SendVoiceMessageConfirmButton", resourceCulture);
            }
        }
        
        internal static string ShowAllReplyButtonText {
            get {
                return ResourceManager.GetString("ShowAllReplyButtonText", resourceCulture);
            }
        }
        
        internal static string SignoutAlertCancelButton {
            get {
                return ResourceManager.GetString("SignoutAlertCancelButton", resourceCulture);
            }
        }
        
        internal static string SignoutAlertMessage {
            get {
                return ResourceManager.GetString("SignoutAlertMessage", resourceCulture);
            }
        }
        
        internal static string SignoutAlertOkButton {
            get {
                return ResourceManager.GetString("SignoutAlertOkButton", resourceCulture);
            }
        }
        
        internal static string SignoutAlertTitle {
            get {
                return ResourceManager.GetString("SignoutAlertTitle", resourceCulture);
            }
        }
        
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        internal static string SubmitSurveyButton {
            get {
                return ResourceManager.GetString("SubmitSurveyButton", resourceCulture);
            }
        }
        
        internal static string SurveyCheckPageTitle {
            get {
                return ResourceManager.GetString("SurveyCheckPageTitle", resourceCulture);
            }
        }
        
        internal static string SurveyCompleted {
            get {
                return ResourceManager.GetString("SurveyCompleted", resourceCulture);
            }
        }
        
        internal static string SurveyExpires {
            get {
                return ResourceManager.GetString("SurveyExpires", resourceCulture);
            }
        }
        
        internal static string SurveyMultipleAswersPlaceholder {
            get {
                return ResourceManager.GetString("SurveyMultipleAswersPlaceholder", resourceCulture);
            }
        }
        
        internal static string SurveyOpenAswerEditorPlaceholder {
            get {
                return ResourceManager.GetString("SurveyOpenAswerEditorPlaceholder", resourceCulture);
            }
        }
        
        internal static string SurveyQuestionOrderLabel {
            get {
                return ResourceManager.GetString("SurveyQuestionOrderLabel", resourceCulture);
            }
        }
        
        internal static string SurveyQuestionsCounterLabel {
            get {
                return ResourceManager.GetString("SurveyQuestionsCounterLabel", resourceCulture);
            }
        }
        
        internal static string SurveyQuestionsVersionLabel {
            get {
                return ResourceManager.GetString("SurveyQuestionsVersionLabel", resourceCulture);
            }
        }
        
        internal static string SurveyResultsBadMessage {
            get {
                return ResourceManager.GetString("SurveyResultsBadMessage", resourceCulture);
            }
        }
        
        internal static string SurveyResultsGoodMessage {
            get {
                return ResourceManager.GetString("SurveyResultsGoodMessage", resourceCulture);
            }
        }
        
        internal static string SurveysFilledInTitle {
            get {
                return ResourceManager.GetString("SurveysFilledInTitle", resourceCulture);
            }
        }
        
        internal static string SurveysGroupTitle {
            get {
                return ResourceManager.GetString("SurveysGroupTitle", resourceCulture);
            }
        }
        
        internal static string SurveySingleAswerPlaceholder {
            get {
                return ResourceManager.GetString("SurveySingleAswerPlaceholder", resourceCulture);
            }
        }
        
        internal static string SurveyStartButton {
            get {
                return ResourceManager.GetString("SurveyStartButton", resourceCulture);
            }
        }
        
        internal static string SurveysToBeFillTitle {
            get {
                return ResourceManager.GetString("SurveysToBeFillTitle", resourceCulture);
            }
        }
        
        internal static string Tagline {
            get {
                return ResourceManager.GetString("Tagline", resourceCulture);
            }
        }
        
        internal static string TakePhoto {
            get {
                return ResourceManager.GetString("TakePhoto", resourceCulture);
            }
        }
        
        internal static string TakePhotoCameraPermissionExceptionMessage {
            get {
                return ResourceManager.GetString("TakePhotoCameraPermissionExceptionMessage", resourceCulture);
            }
        }
        
        internal static string TakePhotoCameraUnsupportedMessage {
            get {
                return ResourceManager.GetString("TakePhotoCameraUnsupportedMessage", resourceCulture);
            }
        }
        
        internal static string TakePhotoCameraUnsupportedTitle {
            get {
                return ResourceManager.GetString("TakePhotoCameraUnsupportedTitle", resourceCulture);
            }
        }
        
        internal static string TapToStartRecording {
            get {
                return ResourceManager.GetString("TapToStartRecording", resourceCulture);
            }
        }
        
        internal static string TapToStartVoiceReproduction {
            get {
                return ResourceManager.GetString("TapToStartVoiceReproduction", resourceCulture);
            }
        }
        
        internal static string TapToStopRecording {
            get {
                return ResourceManager.GetString("TapToStopRecording", resourceCulture);
            }
        }
        
        internal static string TermsAndConditionsAgreeMessage {
            get {
                return ResourceManager.GetString("TermsAndConditionsAgreeMessage", resourceCulture);
            }
        }
        
        internal static string TermsAndConditionsAgreeTitle {
            get {
                return ResourceManager.GetString("TermsAndConditionsAgreeTitle", resourceCulture);
            }
        }
        
        internal static string TermsAndConditionsAndLicenseTitle {
            get {
                return ResourceManager.GetString("TermsAndConditionsAndLicenseTitle", resourceCulture);
            }
        }
        
        internal static string TermsAndConditionsButtonText {
            get {
                return ResourceManager.GetString("TermsAndConditionsButtonText", resourceCulture);
            }
        }
        
        internal static string TermsAndConditionsConfirmMessage {
            get {
                return ResourceManager.GetString("TermsAndConditionsConfirmMessage", resourceCulture);
            }
        }
        
        internal static string TermsAndConditionsError {
            get {
                return ResourceManager.GetString("TermsAndConditionsError", resourceCulture);
            }
        }
        
        internal static string TermsAndConditionsTitle {
            get {
                return ResourceManager.GetString("TermsAndConditionsTitle", resourceCulture);
            }
        }
        
        internal static string TermsConditionsAndLicenseButtonText {
            get {
                return ResourceManager.GetString("TermsConditionsAndLicenseButtonText", resourceCulture);
            }
        }
        
        internal static string TextTypeMessage {
            get {
                return ResourceManager.GetString("TextTypeMessage", resourceCulture);
            }
        }
        
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        internal static string TitleRequiredError {
            get {
                return ResourceManager.GetString("TitleRequiredError", resourceCulture);
            }
        }
        
        internal static string ToBeCompletedSurveysPageTitle {
            get {
                return ResourceManager.GetString("ToBeCompletedSurveysPageTitle", resourceCulture);
            }
        }
        
        internal static string TopicType {
            get {
                return ResourceManager.GetString("TopicType", resourceCulture);
            }
        }
        
        internal static string UnlimitedNotificationsTime {
            get {
                return ResourceManager.GetString("UnlimitedNotificationsTime", resourceCulture);
            }
        }
        
        internal static string UpdateAnalysisAlertConfirmButton {
            get {
                return ResourceManager.GetString("UpdateAnalysisAlertConfirmButton", resourceCulture);
            }
        }
        
        internal static string UpdateAnalysisAlertMessage {
            get {
                return ResourceManager.GetString("UpdateAnalysisAlertMessage", resourceCulture);
            }
        }
        
        internal static string UpdateAnalysisAlertTitle {
            get {
                return ResourceManager.GetString("UpdateAnalysisAlertTitle", resourceCulture);
            }
        }
        
        internal static string UpdateAnalysisSuccessAlertMessage {
            get {
                return ResourceManager.GetString("UpdateAnalysisSuccessAlertMessage", resourceCulture);
            }
        }
        
        internal static string UploadProfileImageError {
            get {
                return ResourceManager.GetString("UploadProfileImageError", resourceCulture);
            }
        }
        
        internal static string UploadProfileImageSuccess {
            get {
                return ResourceManager.GetString("UploadProfileImageSuccess", resourceCulture);
            }
        }
        
        internal static string UrgentMedicalAdviceCondition {
            get {
                return ResourceManager.GetString("UrgentMedicalAdviceCondition", resourceCulture);
            }
        }
        
        internal static string UrgentMedicalAdviceError {
            get {
                return ResourceManager.GetString("UrgentMedicalAdviceError", resourceCulture);
            }
        }
        
        internal static string UrgentMedicalAdviceMessage {
            get {
                return ResourceManager.GetString("UrgentMedicalAdviceMessage", resourceCulture);
            }
        }
        
        internal static string UrgentMedicalAdviceMessage2 {
            get {
                return ResourceManager.GetString("UrgentMedicalAdviceMessage2", resourceCulture);
            }
        }
        
        internal static string UrgentMedicalAdviceMessage3 {
            get {
                return ResourceManager.GetString("UrgentMedicalAdviceMessage3", resourceCulture);
            }
        }
        
        internal static string UrgentMedicalAdviceTitle {
            get {
                return ResourceManager.GetString("UrgentMedicalAdviceTitle", resourceCulture);
            }
        }
        
        internal static string VideoMessageUploadSuccess {
            get {
                return ResourceManager.GetString("VideoMessageUploadSuccess", resourceCulture);
            }
        }
        
        internal static string VideoPlayerPageTitle {
            get {
                return ResourceManager.GetString("VideoPlayerPageTitle", resourceCulture);
            }
        }
        
        internal static string VideoTypeMessage {
            get {
                return ResourceManager.GetString("VideoTypeMessage", resourceCulture);
            }
        }
        
        internal static string VoiceMessageUploadSuccess {
            get {
                return ResourceManager.GetString("VoiceMessageUploadSuccess", resourceCulture);
            }
        }
        
        internal static string VoicePlayError {
            get {
                return ResourceManager.GetString("VoicePlayError", resourceCulture);
            }
        }
        
        internal static string VoiceRecordingCancelButton {
            get {
                return ResourceManager.GetString("VoiceRecordingCancelButton", resourceCulture);
            }
        }
        
        internal static string VoiceRecordingCloseButton {
            get {
                return ResourceManager.GetString("VoiceRecordingCloseButton", resourceCulture);
            }
        }
        
        internal static string VoiceRecordingClosePageTitle {
            get {
                return ResourceManager.GetString("VoiceRecordingClosePageTitle", resourceCulture);
            }
        }
        
        internal static string VoiceRecordingTitle {
            get {
                return ResourceManager.GetString("VoiceRecordingTitle", resourceCulture);
            }
        }
        
        internal static string VoiceTypeMessage {
            get {
                return ResourceManager.GetString("VoiceTypeMessage", resourceCulture);
            }
        }
        
        internal static string Waiting {
            get {
                return ResourceManager.GetString("Waiting", resourceCulture);
            }
        }
        
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        internal static string YesButton {
            get {
                return ResourceManager.GetString("YesButton", resourceCulture);
            }
        }
        
        internal static string YourPatientsTitle {
            get {
                return ResourceManager.GetString("YourPatientsTitle", resourceCulture);
            }
        }
        
        internal static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        internal static string UserCantSignin {
            get {
                return ResourceManager.GetString("UserCantSignin", resourceCulture);
            }
        }
        
        internal static string UserCantReplyToMessage {
            get {
                return ResourceManager.GetString("UserCantReplyToMessage", resourceCulture);
            }
        }
        
        internal static string LoginDocumentsUnavaliable {
            get {
                return ResourceManager.GetString("LoginDocumentsUnavaliable", resourceCulture);
            }
        }
        
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        internal static string Deactivated {
            get {
                return ResourceManager.GetString("Deactivated", resourceCulture);
            }
        }
        
        internal static string Suspended {
            get {
                return ResourceManager.GetString("Suspended", resourceCulture);
            }
        }
        
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        internal static string UpdateDiscaimer {
            get {
                return ResourceManager.GetString("UpdateDiscaimer", resourceCulture);
            }
        }
        
        internal static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        internal static string Tomorrow {
            get {
                return ResourceManager.GetString("Tomorrow", resourceCulture);
            }
        }
        
        internal static string SurveysStats {
            get {
                return ResourceManager.GetString("SurveysStats", resourceCulture);
            }
        }
        
        internal static string SurveysPartecipants {
            get {
                return ResourceManager.GetString("SurveysPartecipants", resourceCulture);
            }
        }
        
        internal static string CompletedSurveys {
            get {
                return ResourceManager.GetString("CompletedSurveys", resourceCulture);
            }
        }
        
        internal static string IncompletedSurveys {
            get {
                return ResourceManager.GetString("IncompletedSurveys", resourceCulture);
            }
        }
        
        internal static string CompletedSurvey {
            get {
                return ResourceManager.GetString("CompletedSurvey", resourceCulture);
            }
        }
        
        internal static string IncompletedSurvey {
            get {
                return ResourceManager.GetString("IncompletedSurvey", resourceCulture);
            }
        }
        
        internal static string SurveysListPageTitle {
            get {
                return ResourceManager.GetString("SurveysListPageTitle", resourceCulture);
            }
        }
        
        internal static string SurveysResultsAndStatistics {
            get {
                return ResourceManager.GetString("SurveysResultsAndStatistics", resourceCulture);
            }
        }
        
        internal static string SurveysNotCompiledError {
            get {
                return ResourceManager.GetString("SurveysNotCompiledError", resourceCulture);
            }
        }
        
        internal static string SurveysResults {
            get {
                return ResourceManager.GetString("SurveysResults", resourceCulture);
            }
        }
        
        internal static string SurveysStatistics {
            get {
                return ResourceManager.GetString("SurveysStatistics", resourceCulture);
            }
        }
    }
}
